# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('birthdate', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_team', models.CharField(blank=True, max_length=255, null=True)),
                ('draft_year', models.IntegerField(blank=True, null=True)),
                ('espn_id', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('jersey', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('average_points', models.FloatField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=255, null=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stats.Franchise')),
            ],
        ),
    ]
