# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_id', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Division')),
            ],
        ),
        migrations.CreateModel(
            name='FranchisePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_players', to='stats.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='FranchisePlayerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average_points', models.FloatField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, null=True)),
                ('franchise_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='stats.FranchisePlayer')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('roster_size', models.IntegerField()),
                ('injured_reserve', models.IntegerField()),
                ('taxi_squad', models.IntegerField()),
                ('start_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_year', models.IntegerField()),
                ('draft_round', models.IntegerField()),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('current_franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_picks', to='stats.Franchise')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_picks', to='stats.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('birthdate', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_team', models.CharField(blank=True, max_length=255, null=True)),
                ('draft_year', models.IntegerField(blank=True, null=True)),
                ('espn_id', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('jersey', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=255, null=True)),
                ('adp', models.FloatField(blank=True, null=True)),
                ('dynasty_adp', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('bid_amount', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('draft_year', models.IntegerField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Franchise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='stats.Player')),
            ],
            options={
                'ordering': ('-bid_amount', 'draft_round', 'draft_pick'),
            },
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField()),
                ('should_have_started', models.BooleanField()),
                ('points', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('points', models.FloatField(blank=True, null=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='stats.Franchise')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.Franchise')),
                ('players', models.ManyToManyField(through='stats.PlayerResult', to='stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_initiator', models.BooleanField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradeoffers', to='stats.Franchise')),
                ('picks', models.ManyToManyField(to='stats.Pick')),
                ('players', models.ManyToManyField(related_name='trades', to='stats.Player')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Trade')),
            ],
            options={
                'ordering': ('trade__timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('free_agent', models.BooleanField()),
                ('adding', models.BooleanField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Franchise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='stats.Player')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='franchises',
            field=models.ManyToManyField(through='stats.TradeOffer', to='stats.Franchise'),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Result'),
        ),
        migrations.AddField(
            model_name='franchiseplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.League'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='players',
            field=models.ManyToManyField(through='stats.FranchisePlayer', to='stats.Player'),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.League'),
        ),
    ]
