# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeoffer',
            name='picks',
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='picks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
