# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
