# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_player_adp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dynasty_adp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
