# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170310_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stats.Franchise'),
        ),
    ]
