# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_auto_20170313_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('bid_amount', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('draft_year', models.IntegerField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Franchise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tradeoffer',
            options={'ordering': ('trade__timestamp',)},
        ),
        migrations.AddField(
            model_name='pick',
            name='draft_pick',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
