# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20170315_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('free_agent', models.BooleanField()),
                ('adding', models.BooleanField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Franchise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Player')),
            ],
        ),
        migrations.AlterModelOptions(
            name='playerdraft',
            options={'ordering': ('-bid_amount', 'draft_round', 'draft_pick')},
        ),
    ]
